apiVersion: apps/v1
kind: Deployment
metadata:
  name: webinar-centos
  namespace: webinar
  labels:
    app: centos
spec:
  selector:
    matchLabels:
      app: centos
  replicas: 1
  template:
    metadata:
      labels:
        app: centos
    spec:
      containers:
        - name: centos
          image: >-
            example-registry-quay-quay.apps.cluster-59v92.59v92.sandbox348.opentlc.com/gantek/webinar
          command: ["/bin/bash", "-c", "sleep 2000000000000"]
          ports:
            - containerPort: 8080
