kind: Secret
apiVersion: v1
metadata:
  name: webinar
  namespace: webinar
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJleGFtcGxlLXJlZ2lzdHJ5LXF1YXktcXVheS5hcHBzLmNsdXN0ZXItNTl2OTIuNTl2OTIuc2FuZGJveDM0OC5vcGVudGxjLmNvbSI6eyJ1c2VybmFtZSI6ImdhbnRlayIsInBhc3N3b3JkIjoic3VwcG9ydCIsImF1dGgiOiJaMkZ1ZEdWck9uTjFjSEJ2Y25RPSIsImVtYWlsIjoic3VwcG9ydEBnYW50ZWsuY29tIn19fQ==
type: kubernetes.io/dockerconfigjson
